### ISSUE TITLE
Setup.py complained silently : No such file or directory

### ISSUE THREAD

**Issue by ggueret** [UbiCastTeam/gstmanager-1.0#1]
Hey UbiCast !

I've tried to install this package using pip an got the following error :

```
  Building wheel for gstmanager1 (setup.py): started
  Building wheel for gstmanager1 (setup.py): finished with status 'error'
  ERROR: Complete output from command /usr/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-1x9edm8t/gstmanager1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ygxcg2zu --python-tag cp36:
  ERROR: Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.6/tokenize.py", line 452, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-1x9edm8t/gstmanager1/setup.py'
  ----------------------------------------
  ERROR: Failed building wheel for gstmanager1
  Running setup.py clean for gstmanager1
  ERROR: Complete output from command /usr/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-1x9edm8t/gstmanager1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all:
  ERROR: Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.6/tokenize.py", line 452, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-1x9edm8t/gstmanager1/setup.py'
  ----------------------------------------
  ERROR: Failed cleaning build dir for gstmanager1
```

The install seems to work anyway.

**Comment by ggueret** [comment]
I be able to reproduce and to understand more precisely.
This is in a pip install context, using requirements.txt with a wrong package egg name.
It is stange that this error is not considered critical by pip. But it is definitely not related to your code.
